-- Migration: Create Central Payments Table
-- Description: Creates a centralized payments table to track all financial transactions in the system
-- Date: 2026-03-03

-- Create payments table
CREATE TABLE IF NOT EXISTS payments (
    id SERIAL PRIMARY KEY,
    
    -- Payment identification
    payment_reference VARCHAR(255) UNIQUE NOT NULL,
    transaction_id VARCHAR(255) DEFAULT NULL, -- Payment gateway transaction ID
    
    -- Payment type and entity references
    payment_type VARCHAR(50) NOT NULL, -- 'team_subscription', 'field_booking', 'package_purchase', 'membership_fee', etc.
    entity_type VARCHAR(50) DEFAULT NULL, -- 'member', 'team_member', 'guest'
    entity_id INTEGER DEFAULT NULL, -- ID of the paying entity
    
    -- Related entity (what they're paying for)
    related_entity_type VARCHAR(50) DEFAULT NULL, -- 'team', 'field_booking', 'package', 'membership'
    related_entity_id VARCHAR(255) DEFAULT NULL, -- Can be integer or UUID
    
    -- Financial details
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'EGP',
    payment_method VARCHAR(50) DEFAULT NULL, -- 'credit_card', 'cash', 'bank_transfer', 'wallet', etc.
    
    -- Payment gateway details
    gateway_name VARCHAR(50) DEFAULT NULL, -- 'paymob', 'fawry', 'stripe', 'cash', etc.
    gateway_response TEXT DEFAULT NULL, -- Full gateway response (JSON)
    
    -- Status tracking
    status VARCHAR(50) NOT NULL DEFAULT 'pending', -- 'pending', 'processing', 'completed', 'failed', 'refunded', 'cancelled'
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP DEFAULT NULL,
    refunded_at TIMESTAMP DEFAULT NULL,
    
    -- Staff tracking
    processed_by_staff_id INTEGER DEFAULT NULL, -- For manual/cash payments
    refunded_by_staff_id INTEGER DEFAULT NULL,
    
    -- Additional metadata
    description TEXT DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    metadata JSONB DEFAULT NULL -- Flexible field for additional data
);

-- Add comments for documentation
COMMENT ON TABLE payments IS 'Central table tracking all payments across the system';
COMMENT ON COLUMN payments.payment_reference IS 'Unique payment reference generated by the system';
COMMENT ON COLUMN payments.transaction_id IS 'External payment gateway transaction ID';
COMMENT ON COLUMN payments.payment_type IS 'Type of payment: team_subscription, field_booking, package_purchase, membership_fee, etc.';
COMMENT ON COLUMN payments.entity_type IS 'Type of entity making the payment: member, team_member, guest';
COMMENT ON COLUMN payments.entity_id IS 'ID of the entity making the payment';
COMMENT ON COLUMN payments.related_entity_type IS 'Type of entity being paid for: team, field_booking, package, membership';
COMMENT ON COLUMN payments.related_entity_id IS 'ID of the entity being paid for (can be integer or UUID)';
COMMENT ON COLUMN payments.amount IS 'Payment amount in the specified currency';
COMMENT ON COLUMN payments.currency IS 'Currency code (ISO 4217)';
COMMENT ON COLUMN payments.payment_method IS 'Method used: credit_card, cash, bank_transfer, wallet, etc.';
COMMENT ON COLUMN payments.gateway_name IS 'Payment gateway used: paymob, fawry, stripe, cash, etc.';
COMMENT ON COLUMN payments.gateway_response IS 'Full response from payment gateway (for debugging)';
COMMENT ON COLUMN payments.status IS 'Payment status: pending, processing, completed, failed, refunded, cancelled';
COMMENT ON COLUMN payments.completed_at IS 'Timestamp when payment was successfully completed';
COMMENT ON COLUMN payments.refunded_at IS 'Timestamp when payment was refunded';
COMMENT ON COLUMN payments.processed_by_staff_id IS 'Staff member who processed manual/cash payment';
COMMENT ON COLUMN payments.refunded_by_staff_id IS 'Staff member who processed the refund';
COMMENT ON COLUMN payments.metadata IS 'Additional flexible data stored as JSON';

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_payments_payment_reference ON payments(payment_reference);
CREATE INDEX IF NOT EXISTS idx_payments_transaction_id ON payments(transaction_id);
CREATE INDEX IF NOT EXISTS idx_payments_payment_type ON payments(payment_type);
CREATE INDEX IF NOT EXISTS idx_payments_entity ON payments(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_payments_related_entity ON payments(related_entity_type, related_entity_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_created_at ON payments(created_at);
CREATE INDEX IF NOT EXISTS idx_payments_completed_at ON payments(completed_at);
CREATE INDEX IF NOT EXISTS idx_payments_gateway ON payments(gateway_name);

-- Create composite indexes for common queries
CREATE INDEX IF NOT EXISTS idx_payments_type_status ON payments(payment_type, status);
CREATE INDEX IF NOT EXISTS idx_payments_entity_type_status ON payments(entity_type, entity_id, status);

-- Add trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_payments_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_payments_updated_at
    BEFORE UPDATE ON payments
    FOR EACH ROW
    EXECUTE FUNCTION update_payments_updated_at();

-- Sample data types (for reference - not inserted)
/*
payment_type values:
- 'team_subscription' - Team membership subscription
- 'field_booking' - Sports field/facility booking
- 'package_purchase' - Privilege package purchase
- 'membership_fee' - Annual/monthly membership fee
- 'training_session' - Individual training session
- 'tournament_registration' - Tournament entry fee
- 'equipment_rental' - Sports equipment rental
- 'late_fee' - Late payment penalty
- 'refund' - Refund transaction

status values:
- 'pending' - Payment initiated, awaiting processing
- 'processing' - Payment being processed by gateway
- 'completed' - Payment successfully completed
- 'failed' - Payment failed
- 'refunded' - Payment refunded to customer
- 'cancelled' - Payment cancelled by user or system

payment_method values:
- 'credit_card' - Credit/debit card
- 'cash' - Cash payment at facility
- 'bank_transfer' - Bank transfer
- 'wallet' - Digital wallet (Vodafone Cash, etc.)
- 'installment' - Installment payment
*/
